/********************************************************************
* R3BTPCSetupDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error R3BTPCSetupDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableR3BTPCSetupDict();
extern void G__cpp_setup_inheritanceR3BTPCSetupDict();
extern void G__cpp_setup_typetableR3BTPCSetupDict();
extern void G__cpp_setup_memvarR3BTPCSetupDict();
extern void G__cpp_setup_globalR3BTPCSetupDict();
extern void G__cpp_setup_memfuncR3BTPCSetupDict();
extern void G__cpp_setup_funcR3BTPCSetupDict();
extern void G__set_cpp_environmentR3BTPCSetupDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "R3BTPCSetup.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__R3BTPCSetupDictLN_TClass;
extern G__linked_taginfo G__R3BTPCSetupDictLN_TBuffer;
extern G__linked_taginfo G__R3BTPCSetupDictLN_TMemberInspector;
extern G__linked_taginfo G__R3BTPCSetupDictLN_TObject;
extern G__linked_taginfo G__R3BTPCSetupDictLN_TString;
extern G__linked_taginfo G__R3BTPCSetupDictLN_string;
extern G__linked_taginfo G__R3BTPCSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__R3BTPCSetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__R3BTPCSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__R3BTPCSetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__R3BTPCSetupDictLN_R3BTPCSetup;

/* STUB derived class for protected member access */
