//
// File generated by rootcint at Mon Feb  5 16:46:30 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TPCSetupDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TPCSetupDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TPCSetup_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_TPCSetup(void *p);
   static void deleteArray_TPCSetup(void *p);
   static void destruct_TPCSetup(void *p);
   static void streamer_TPCSetup(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TPCSetup*)
   {
      ::TPCSetup *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPCSetup >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TPCSetup", ::TPCSetup::Class_Version(), "./TPCSetup.h", 16,
                  typeid(::TPCSetup), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TPCSetup::Dictionary, isa_proxy, 0,
                  sizeof(::TPCSetup) );
      instance.SetDelete(&delete_TPCSetup);
      instance.SetDeleteArray(&deleteArray_TPCSetup);
      instance.SetDestructor(&destruct_TPCSetup);
      instance.SetStreamerFunc(&streamer_TPCSetup);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TPCSetup*)
   {
      return GenerateInitInstanceLocal((::TPCSetup*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TPCSetup*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TPCSetup::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TPCSetup::Class_Name()
{
   return "TPCSetup";
}

//______________________________________________________________________________
const char *TPCSetup::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TPCSetup*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TPCSetup::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TPCSetup*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TPCSetup::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TPCSetup*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TPCSetup::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TPCSetup*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TPCSetup::Streamer(TBuffer &R__b)
{
   // Stream an object of class TPCSetup.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> TargetRadius;
      R__b >> TargetLength;
      R__b >> ChamberInnerRadius;
      R__b >> ChamberThickness;
      R__b >> ChamberLength;
      R__b >> InnerRohacellThickness;
      R__b >> KaptonThickness;
      R__b >> OuterRohacellThickness;
      R__b >> TPCRadiusExt;
      R__b >> WindowThickness;
      R__b >> TPCLx;
      R__b >> TPCLy;
      R__b >> TPCLz;
      R__b >> TargetAngle;
      R__b >> TargetOffsetX;
      R__b >> TargetOffsetY;
      R__b >> TargetOffsetZ;
      R__b >> GladAngle;
      R__b >> GladOffsetX;
      R__b >> GladOffsetY;
      R__b >> GladOffsetZ;
      R__b >> FieldAngle;
      R__b >> FieldOffsetX;
      R__b >> FieldOffsetY;
      R__b >> FieldOffsetZ;
      OutputFileName.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, TPCSetup::IsA());
   } else {
      R__c = R__b.WriteVersion(TPCSetup::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << TargetRadius;
      R__b << TargetLength;
      R__b << ChamberInnerRadius;
      R__b << ChamberThickness;
      R__b << ChamberLength;
      R__b << InnerRohacellThickness;
      R__b << KaptonThickness;
      R__b << OuterRohacellThickness;
      R__b << TPCRadiusExt;
      R__b << WindowThickness;
      R__b << TPCLx;
      R__b << TPCLy;
      R__b << TPCLz;
      R__b << TargetAngle;
      R__b << TargetOffsetX;
      R__b << TargetOffsetY;
      R__b << TargetOffsetZ;
      R__b << GladAngle;
      R__b << GladOffsetX;
      R__b << GladOffsetY;
      R__b << GladOffsetZ;
      R__b << FieldAngle;
      R__b << FieldOffsetX;
      R__b << FieldOffsetY;
      R__b << FieldOffsetZ;
      OutputFileName.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TPCSetup::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TPCSetup.
      TClass *R__cl = ::TPCSetup::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TargetRadius", &TargetRadius);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TargetLength", &TargetLength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ChamberInnerRadius", &ChamberInnerRadius);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ChamberThickness", &ChamberThickness);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ChamberLength", &ChamberLength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "InnerRohacellThickness", &InnerRohacellThickness);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "KaptonThickness", &KaptonThickness);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "OuterRohacellThickness", &OuterRohacellThickness);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPCRadiusExt", &TPCRadiusExt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "WindowThickness", &WindowThickness);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPCLx", &TPCLx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPCLy", &TPCLy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPCLz", &TPCLz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TargetAngle", &TargetAngle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TargetOffsetX", &TargetOffsetX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TargetOffsetY", &TargetOffsetY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TargetOffsetZ", &TargetOffsetZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GladAngle", &GladAngle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GladOffsetX", &GladOffsetX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GladOffsetY", &GladOffsetY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GladOffsetZ", &GladOffsetZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FieldAngle", &FieldAngle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FieldOffsetX", &FieldOffsetX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FieldOffsetY", &FieldOffsetY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FieldOffsetZ", &FieldOffsetZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "OutputFileName", &OutputFileName);
      R__insp.InspectMember(OutputFileName, "OutputFileName.");
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_TPCSetup(void *p) {
      delete ((::TPCSetup*)p);
   }
   static void deleteArray_TPCSetup(void *p) {
      delete [] ((::TPCSetup*)p);
   }
   static void destruct_TPCSetup(void *p) {
      typedef ::TPCSetup current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TPCSetup(TBuffer &buf, void *obj) {
      ((::TPCSetup*)obj)->::TPCSetup::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TPCSetup

/********************************************************
* TPCSetupDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTPCSetupDict();

extern "C" void G__set_cpp_environmentTPCSetupDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TPCSetup.h");
  G__cpp_reset_tagtableTPCSetupDict();
}
#include <new>
extern "C" int G__cpp_dllrevTPCSetupDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TPCSetup */
static int G__TPCSetupDict_184_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPCSetup* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TPCSetup((int) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TPCSetup((int) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TPCSetup*) G__getstructoffset())->ReadConfigurationFile(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((TPCSetup*) G__getstructoffset())->GetOutputFileName();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetTargetLength());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetTargetRadius());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetTargetAngle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetTargetOffsetX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetTargetOffsetY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetTargetOffsetZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetFieldAngle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetFieldOffsetX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetFieldOffsetY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetFieldOffsetZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetGladAngle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetGladOffsetX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetGladOffsetY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TPCSetup*) G__getstructoffset())->GetGladOffsetZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TPCSetup::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPCSetup::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TPCSetup::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TPCSetup::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TPCSetup*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPCSetup::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPCSetup::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPCSetup::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TPCSetupDict_184_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPCSetup::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TPCSetupDict_184_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TPCSetup* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TPCSetup(*(TPCSetup*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TPCSetup G__TTPCSetup;
static int G__TPCSetupDict_184_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TPCSetup*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TPCSetup*) (soff+(sizeof(TPCSetup)*i)))->~G__TTPCSetup();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TPCSetup*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TPCSetup*) (soff))->~G__TTPCSetup();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TPCSetupDict_184_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPCSetup* dest = (TPCSetup*) G__getstructoffset();
   *dest = *(TPCSetup*) libp->para[0].ref;
   const TPCSetup& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TPCSetup */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTPCSetupDict {
 public:
  G__Sizep2memfuncTPCSetupDict(): p(&G__Sizep2memfuncTPCSetupDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTPCSetupDict::*p)();
};

size_t G__get_sizep2memfuncTPCSetupDict()
{
  G__Sizep2memfuncTPCSetupDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTPCSetupDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup))) {
     TPCSetup *G__Lderived;
     G__Lderived=(TPCSetup*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup),G__get_linked_tagnum(&G__TPCSetupDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTPCSetupDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TPCSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TPCSetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TPCSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TPCSetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TPCSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TPCSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TPCSetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TPCSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TPCSetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TPCSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TPCSetup */
static void G__setup_memvarTPCSetup(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup));
   { TPCSetup *p; p=(TPCSetup*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->TargetRadius)-(long)(p)),100,0,0,-1,-1,-1,1,"TargetRadius=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TargetLength)-(long)(p)),100,0,0,-1,-1,-1,1,"TargetLength=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ChamberInnerRadius)-(long)(p)),100,0,0,-1,-1,-1,1,"ChamberInnerRadius=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ChamberThickness)-(long)(p)),100,0,0,-1,-1,-1,1,"ChamberThickness=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ChamberLength)-(long)(p)),100,0,0,-1,-1,-1,1,"ChamberLength=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->InnerRohacellThickness)-(long)(p)),100,0,0,-1,-1,-1,1,"InnerRohacellThickness=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->KaptonThickness)-(long)(p)),100,0,0,-1,-1,-1,1,"KaptonThickness=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->OuterRohacellThickness)-(long)(p)),100,0,0,-1,-1,-1,1,"OuterRohacellThickness=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TPCRadiusExt)-(long)(p)),100,0,0,-1,-1,-1,1,"TPCRadiusExt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->WindowThickness)-(long)(p)),100,0,0,-1,-1,-1,1,"WindowThickness=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TPCLx)-(long)(p)),100,0,0,-1,-1,-1,1,"TPCLx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TPCLy)-(long)(p)),100,0,0,-1,-1,-1,1,"TPCLy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TPCLz)-(long)(p)),100,0,0,-1,-1,-1,1,"TPCLz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TargetAngle)-(long)(p)),100,0,0,-1,-1,-1,1,"TargetAngle=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TargetOffsetX)-(long)(p)),100,0,0,-1,-1,-1,1,"TargetOffsetX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TargetOffsetY)-(long)(p)),100,0,0,-1,-1,-1,1,"TargetOffsetY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TargetOffsetZ)-(long)(p)),100,0,0,-1,-1,-1,1,"TargetOffsetZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->GladAngle)-(long)(p)),100,0,0,-1,-1,-1,1,"GladAngle=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->GladOffsetX)-(long)(p)),100,0,0,-1,-1,-1,1,"GladOffsetX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->GladOffsetY)-(long)(p)),100,0,0,-1,-1,-1,1,"GladOffsetY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->GladOffsetZ)-(long)(p)),100,0,0,-1,-1,-1,1,"GladOffsetZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FieldAngle)-(long)(p)),100,0,0,-1,-1,-1,1,"FieldAngle=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FieldOffsetX)-(long)(p)),100,0,0,-1,-1,-1,1,"FieldOffsetX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FieldOffsetY)-(long)(p)),100,0,0,-1,-1,-1,1,"FieldOffsetY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FieldOffsetZ)-(long)(p)),100,0,0,-1,-1,-1,1,"FieldOffsetZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->OutputFileName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TPCSetupDictLN_TString),-1,-1,1,"OutputFileName=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TPCSetupDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTPCSetupDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTPCSetup(void) {
   /* TPCSetup */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup));
   G__memfunc_setup("TPCSetup",760,G__TPCSetupDict_184_0_1, 105, G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup), -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadConfigurationFile",2132,G__TPCSetupDict_184_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - - i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetOutputFileName",1714,G__TPCSetupDict_184_0_3, 117, G__get_linked_tagnum(&G__TPCSetupDictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTargetLength",1513,G__TPCSetupDict_184_0_4, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTargetRadius",1519,G__TPCSetupDict_184_0_5, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTargetAngle",1390,G__TPCSetupDict_184_0_6, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTargetOffsetX",1606,G__TPCSetupDict_184_0_7, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTargetOffsetY",1607,G__TPCSetupDict_184_0_8, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTargetOffsetZ",1608,G__TPCSetupDict_184_0_9, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFieldAngle",1259,G__TPCSetupDict_184_0_10, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFieldOffsetX",1475,G__TPCSetupDict_184_0_11, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFieldOffsetY",1476,G__TPCSetupDict_184_0_12, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFieldOffsetZ",1477,G__TPCSetupDict_184_0_13, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGladAngle",1151,G__TPCSetupDict_184_0_14, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGladOffsetX",1367,G__TPCSetupDict_184_0_15, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGladOffsetY",1368,G__TPCSetupDict_184_0_16, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGladOffsetZ",1369,G__TPCSetupDict_184_0_17, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TPCSetupDict_184_0_18, 85, G__get_linked_tagnum(&G__TPCSetupDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TPCSetup::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TPCSetupDict_184_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPCSetup::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TPCSetupDict_184_0_20, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TPCSetup::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TPCSetupDict_184_0_21, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TPCSetup::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TPCSetupDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TPCSetupDict_184_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TPCSetupDict_184_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPCSetup::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TPCSetupDict_184_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPCSetup::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TPCSetupDict_184_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPCSetup::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TPCSetupDict_184_0_29, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPCSetup::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TPCSetup", 760, G__TPCSetupDict_184_0_30, (int) ('i'), G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup), -1, 0, 1, 1, 1, 0, "u 'TPCSetup' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TPCSetup", 886, G__TPCSetupDict_184_0_31, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TPCSetupDict_184_0_32, (int) ('u'), G__get_linked_tagnum(&G__TPCSetupDictLN_TPCSetup), -1, 1, 1, 1, 1, 0, "u 'TPCSetup' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTPCSetupDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTPCSetupDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTPCSetupDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TPCSetupDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TPCSetupDictLN_TPCSetup = { "TPCSetup" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTPCSetupDict() {
  G__TPCSetupDictLN_TClass.tagnum = -1 ;
  G__TPCSetupDictLN_TBuffer.tagnum = -1 ;
  G__TPCSetupDictLN_TMemberInspector.tagnum = -1 ;
  G__TPCSetupDictLN_TObject.tagnum = -1 ;
  G__TPCSetupDictLN_TString.tagnum = -1 ;
  G__TPCSetupDictLN_string.tagnum = -1 ;
  G__TPCSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TPCSetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TPCSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TPCSetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TPCSetupDictLN_TPCSetup.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTPCSetupDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_TString);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_string);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TPCSetupDictLN_TPCSetup),sizeof(TPCSetup),-1,62464,(char*)NULL,G__setup_memvarTPCSetup,G__setup_memfuncTPCSetup);
}
extern "C" void G__cpp_setupTPCSetupDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTPCSetupDict()");
  G__set_cpp_environmentTPCSetupDict();
  G__cpp_setup_tagtableTPCSetupDict();

  G__cpp_setup_inheritanceTPCSetupDict();

  G__cpp_setup_typetableTPCSetupDict();

  G__cpp_setup_memvarTPCSetupDict();

  G__cpp_setup_memfuncTPCSetupDict();
  G__cpp_setup_globalTPCSetupDict();
  G__cpp_setup_funcTPCSetupDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTPCSetupDict();
  return;
}
class G__cpp_setup_initTPCSetupDict {
  public:
    G__cpp_setup_initTPCSetupDict() { G__add_setup_func("TPCSetupDict",(G__incsetup)(&G__cpp_setupTPCSetupDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTPCSetupDict() { G__remove_setup_func("TPCSetupDict"); }
};
G__cpp_setup_initTPCSetupDict G__cpp_setup_initializerTPCSetupDict;

