/********************************************************************
* TPCSetupDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TPCSetupDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTPCSetupDict();
extern void G__cpp_setup_inheritanceTPCSetupDict();
extern void G__cpp_setup_typetableTPCSetupDict();
extern void G__cpp_setup_memvarTPCSetupDict();
extern void G__cpp_setup_globalTPCSetupDict();
extern void G__cpp_setup_memfuncTPCSetupDict();
extern void G__cpp_setup_funcTPCSetupDict();
extern void G__set_cpp_environmentTPCSetupDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TPCSetup.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TPCSetupDictLN_TClass;
extern G__linked_taginfo G__TPCSetupDictLN_TBuffer;
extern G__linked_taginfo G__TPCSetupDictLN_TMemberInspector;
extern G__linked_taginfo G__TPCSetupDictLN_TObject;
extern G__linked_taginfo G__TPCSetupDictLN_TString;
extern G__linked_taginfo G__TPCSetupDictLN_string;
extern G__linked_taginfo G__TPCSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TPCSetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPCSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TPCSetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPCSetupDictLN_TPCSetup;

/* STUB derived class for protected member access */
